
site_name: C++ 핵심 가이드라인
site_description: "C++ 핵심 가이드라인 한글화 프로젝트"
site_author: C++ Korea
site_url: https://luncliff.github.io/coreguidelines

repo_name: CppKorea/CppCoreGuidelines
repo_url: http://github.com/CppKorea/CppCoreGuidelines

copyright: "Copyright (c) Standard C++ Foundation and its contributors"

theme:
  name: readthedocs

docs_dir: sections
nav:
  - Home: ReadMe.md
  - Introduction: Introduction.md
  - References: References.md
  - Sections:
    - Architecture: Architecture.md
    - Class: Class.md
    - Concurrency: Concurrency.md
    - Const: Const.md
    - CPL: CPL.md
    - Enum: Enum.md
    - Errors: Errors.md
    - Expr: Expr.md
    - Functions: Functions.md
    - Glossary: Glossary.md
    - GSL: GSL.md
    - Interfaces: Interfaces.md
    - Naming: Naming.md
    - Not: Not.md
    - Performance: Performance.md
    - Philosophy: Philosophy.md
    - Profile: Profile.md
    - Resource: Resource.md
    - SL: SL.md
    - Source: Source.md
    - Template: Template.md
    - Unclassified: Unclassified.md
  - Appendix:
    - Discussion: Discussion.md
    - Libraries: Libraries.md
    - Modernizing: Modernizing.md
    - Tools: Tools.md
